/*
  # Add new services

  1. Changes
    - Add new services to business_services table
    - Add unique constraint on business_id and name combination
    - Add index for performance optimization

  2. Notes
    - Services are added without business_id to serve as templates
    - Each service will get a unique slug automatically via the GENERATED ALWAYS AS clause
*/

-- Add unique constraint to prevent duplicate services for the same business
ALTER TABLE business_services ADD CONSTRAINT business_services_business_name_unique UNIQUE (business_id, name);

-- Insert new services
INSERT INTO business_services (business_id, name, description)
VALUES 
  (NULL, '20 Yard Dumpster Rental Services', 'Professional dumpster rental services for construction and cleanup projects'),
  (NULL, '24 Hour Animal Control Services', 'Emergency animal control and removal services available 24/7'),
  (NULL, '24 Hour Furnace Repair', 'Emergency furnace repair services available around the clock'),
  (NULL, '24 Hour Pest Control Services', 'Emergency pest control services available 24/7'),
  (NULL, 'Above Ground Pool Contractors', 'Professional installation and maintenance of above ground pools'),
  (NULL, 'Above Ground Pool Repair', 'Expert repair services for above ground swimming pools'),
  (NULL, 'Affordable Plumbing', 'Cost-effective plumbing services for residential and commercial properties'),
  (NULL, 'Affordable Roofing', 'Quality roofing services at competitive prices'),
  (NULL, 'Air Conditioning Installation', 'Professional AC unit installation services'),
  (NULL, 'Air Conditioning Repair', 'Expert repair services for all types of air conditioning systems'),
  (NULL, 'Air Duct Cleaning', 'Professional cleaning services for air ducts and HVAC systems'),
  (NULL, 'Alarm Companies', 'Security system installation and monitoring services'),
  (NULL, 'Aluminum Fence Companies', 'Installation and repair of aluminum fencing'),
  (NULL, 'Animal Control', 'Professional wildlife and pest animal management services'),
  (NULL, 'Animal Fencing', 'Installation of pet and animal containment fencing systems'),
  (NULL, 'Ant Exterminators', 'Specialized ant control and elimination services'),
  (NULL, 'Antique Lamp Repair', 'Expert restoration and repair of antique lighting fixtures'),
  (NULL, 'Antique Restoration', 'Professional restoration services for antique furniture and items'),
  (NULL, 'Apartment Cleaners', 'Comprehensive cleaning services for apartments and rental properties'),
  (NULL, 'Appliance Installers', 'Professional installation services for home appliances'),
  (NULL, 'Appliance Removal', 'Safe removal and disposal of old appliances'),
  (NULL, 'Appliance Repair', 'Expert repair services for household appliances'),
  (NULL, 'Appliance Repair Companies', 'Professional appliance repair and maintenance services'),
  (NULL, 'Appliance Sales', 'Retail sales of home and commercial appliances'),
  (NULL, 'Appliances', 'Sales and service of home and commercial appliances'),
  (NULL, 'Appraisals - Antiques/Jewelry/Items', 'Professional valuation services for antiques and collectibles'),
  (NULL, 'Aquarium Services', 'Installation and maintenance of aquariums'),
  (NULL, 'Arborists', 'Professional tree care and maintenance services'),
  (NULL, 'Architects', 'Professional architectural design services'),
  (NULL, 'Artificial Grass Companies', 'Installation and maintenance of artificial turf'),
  (NULL, 'Asbestos Removal', 'Professional asbestos abatement services'),
  (NULL, 'Asbestos Removal Contractors', 'Licensed asbestos removal and disposal services'),
  (NULL, 'Asbestos Testers', 'Professional asbestos testing and inspection services'),
  (NULL, 'Asphalt Contractors', 'Professional asphalt paving and repair services'),
  (NULL, 'Asphalt Driveway Contractors', 'Specialized driveway paving and repair services'),
  (NULL, 'Asphalt Patching', 'Professional asphalt repair and patching services'),
  (NULL, 'Asphalt Repair Companies', 'Expert asphalt maintenance and repair services'),
  (NULL, 'Asphalt Resurfacing Companies', 'Professional asphalt resurfacing and restoration services'),
  (NULL, 'Asphalt Sealing', 'Protective sealing services for asphalt surfaces'),
  (NULL, 'Attic Fan Installation', 'Professional installation of attic ventilation systems'),
  (NULL, 'Attic Fan Repair', 'Expert repair services for attic fans and ventilation'),
  (NULL, 'Attic Insulation Companies', 'Professional attic insulation installation services'),
  (NULL, 'Attic Ladder Installation', 'Installation of attic access ladders and stairs'),
  (NULL, 'Attic Ventilation Contractors', 'Expert attic ventilation system installation and repair'),
  (NULL, 'Awning Companies', 'Professional awning installation and repair services'),
  (NULL, 'Awning Repair', 'Expert repair services for all types of awnings'),
  (NULL, 'Awnings', 'Sales and installation of residential and commercial awnings'),
  (NULL, 'Backsplash Installation', 'Professional kitchen and bathroom backsplash installation'),
  (NULL, 'Backyard Design Companies', 'Professional landscape and backyard design services'),
  (NULL, 'Backyard Landscapers', 'Expert backyard landscaping and maintenance services'),
  (NULL, 'Balcony Contractors', 'Professional balcony construction and repair services'),
  (NULL, 'Barn Builders', 'Custom barn design and construction services'),
  (NULL, 'Barn Repair', 'Professional barn maintenance and repair services'),
  (NULL, 'Barndominium Builders', 'Custom barndominium design and construction services'),
  (NULL, 'Baseboard Installation', 'Professional baseboard and trim installation services'),
  (NULL, 'Basement Companies', 'Professional basement renovation and finishing services'),
  (NULL, 'Basement Finishing', 'Complete basement finishing and remodeling services'),
  (NULL, 'Basement Leak Repair', 'Expert basement waterproofing and leak repair'),
  (NULL, 'Basement Waterproofing', 'Professional basement moisture protection services'),
  (NULL, 'Basketball Goals', 'Installation and repair of basketball hoops and equipment'),
  (NULL, 'Bat Control', 'Professional bat removal and exclusion services'),
  (NULL, 'Bathroom Design Companies', 'Professional bathroom design and planning services'),
  (NULL, 'Bathroom Fan Installation', 'Expert installation of bathroom ventilation systems'),
  (NULL, 'Bathroom Remodeling', 'Complete bathroom renovation services'),
  (NULL, 'Bathroom Repair Services', 'Professional bathroom maintenance and repair'),
  (NULL, 'Bathroom Tile Contractors', 'Expert bathroom tile installation services'),
  (NULL, 'Bathroom Tile Repair', 'Professional repair services for bathroom tile'),
  (NULL, 'Bathroom Vanity Installation', 'Expert installation of bathroom vanities and cabinets'),
  (NULL, 'Bathtub Installation', 'Professional bathtub installation services'),
  (NULL, 'Bathtub Refinishing', 'Expert bathtub restoration and refinishing services'),
  (NULL, 'Bathtub Repair Companies', 'Professional bathtub repair and maintenance'),
  (NULL, 'Bathtub Replacement', 'Complete bathtub removal and replacement services'),
  (NULL, 'Bed Bug Control', 'Professional bed bug elimination services'),
  (NULL, 'Bee Removal', 'Safe and professional bee removal services'),
  (NULL, 'Biohazard Remediation', 'Professional biohazard cleanup and disposal services'),
  (NULL, 'Bird Control', 'Professional bird deterrent and removal services'),
  (NULL, 'Black Mold Inspection', 'Professional mold testing and inspection services'),
  (NULL, 'Blacktop Companies', 'Professional asphalt paving and maintenance'),
  (NULL, 'Blind Cleaning', 'Professional blind and shade cleaning services'),
  (NULL, 'Blind Installation', 'Expert installation of window blinds and shades'),
  (NULL, 'Blind Repair', 'Professional repair services for window blinds'),
  (NULL, 'Block Wall Companies', 'Professional block wall construction and repair'),
  (NULL, 'Blown-In Insulation', 'Professional blown-in insulation installation'),
  (NULL, 'Boat Dock Repair', 'Expert repair services for boat docks and lifts'),
  (NULL, 'Boiler Installation', 'Professional boiler installation services'),
  (NULL, 'Boiler Repair', 'Expert boiler repair and maintenance services'),
  (NULL, 'Bosch Appliance Repair', 'Specialized repair services for Bosch appliances'),
  (NULL, 'Brick Paver Companies', 'Professional brick paving installation services'),
  (NULL, 'Brush Chipping Services', 'Professional brush and tree debris removal'),
  (NULL, 'Buffing and Polishing', 'Professional floor buffing and polishing services'),
  (NULL, 'Bug Control', 'Comprehensive pest control services'),
  (NULL, 'Builders', 'Professional construction and building services'),
  (NULL, 'Building Contractors', 'Licensed building and construction contractors'),
  (NULL, 'Business Roof Repair', 'Commercial roofing repair services'),
  (NULL, 'Cabinet Installers', 'Professional cabinet installation services'),
  (NULL, 'Cabinet Makers', 'Custom cabinet design and manufacturing'),
  (NULL, 'Cabinet Painting', 'Professional cabinet refinishing services'),
  (NULL, 'Cabinet Refacing', 'Cabinet door and drawer front replacement'),
  (NULL, 'Cabinet Refacing and Refinishing', 'Complete cabinet restoration services'),
  (NULL, 'Cabinet Refinishers', 'Professional cabinet restoration services'),
  (NULL, 'Cabinet Repair', 'Expert cabinet repair and maintenance'),
  (NULL, 'CAD Drafting Services', 'Professional computer-aided design services'),
  (NULL, 'Carpentry', 'Professional woodworking and carpentry services'),
  (NULL, 'Carpet Cleaning', 'Professional carpet cleaning and maintenance'),
  (NULL, 'Carpet Dyeing', 'Expert carpet color restoration services'),
  (NULL, 'Carpet Installation', 'Professional carpet installation services'),
  (NULL, 'Carpet Layers', 'Expert carpet installation professionals'),
  (NULL, 'Carpet Removal', 'Professional carpet removal services'),
  (NULL, 'Carpet Repair Companies', 'Expert carpet repair and restoration'),
  (NULL, 'Carpet Shampoo Services', 'Professional carpet cleaning services'),
  (NULL, 'Carpet Steam Cleaners', 'Professional steam cleaning services'),
  (NULL, 'Carpet Stretching Services', 'Expert carpet stretching and repair'),
  (NULL, 'Carport Installation', 'Professional carport construction services'),
  (NULL, 'Carport Repair', 'Expert carport repair and maintenance'),
  (NULL, 'Caulking Services', 'Professional caulking and sealing services'),
  (NULL, 'Ceiling Companies', 'Professional ceiling installation and repair'),
  (NULL, 'Ceiling Fan Companies', 'Expert ceiling fan installation services'),
  (NULL, 'Ceiling Fan Repair', 'Professional ceiling fan repair services'),
  (NULL, 'Ceiling Fans', 'Sales and installation of ceiling fans'),
  (NULL, 'Ceiling Painters', 'Professional ceiling painting services'),
  (NULL, 'Ceiling Repair Companies', 'Expert ceiling repair and restoration'),
  (NULL, 'Ceiling Tile Installation', 'Professional ceiling tile installation'),
  (NULL, 'Cement Companies', 'Professional concrete and cement services'),
  (NULL, 'Central Vacuum Cleaning', 'Central vacuum system maintenance'),
  (NULL, 'Central Vacuum Installation', 'Professional central vacuum installation'),
  (NULL, 'Central Vacuum Repair', 'Expert central vacuum system repair'),
  (NULL, 'Ceramic Tile', 'Professional ceramic tile installation'),
  (NULL, 'Ceramic Tile Companies', 'Expert ceramic tile installation services'),
  (NULL, 'Ceramic Tile Repair', 'Professional ceramic tile repair services'),
  (NULL, 'Chain Link Fence Companies', 'Chain link fence installation services'),
  (NULL, 'Chain Link Fence Repair', 'Professional fence repair services'),
  (NULL, 'Chair Lift Companies', 'Stair lift installation and maintenance'),
  (NULL, 'Chandelier Installation', 'Professional lighting installation services'),
  (NULL, 'Childproofing', 'Home childproofing installation services'),
  (NULL, 'Chimney Cap Replacement', 'Professional chimney cap services'),
  (NULL, 'Chimney Caps', 'Chimney cap installation and repair'),
  (NULL, 'Chimney Cleaning', 'Professional chimney sweep services'),
  (NULL, 'Chimney Inspection', 'Expert chimney inspection services'),
  (NULL, 'Chimney Liner Installation', 'Professional chimney liner services'),
  (NULL, 'Chimney Repair', 'Expert chimney repair and maintenance'),
  (NULL, 'Chimney Sweep', 'Professional chimney cleaning services'),
  (NULL, 'Christmas Lights Installers', 'Holiday lighting installation services'),
  (NULL, 'Cleaning', 'Professional cleaning services'),
  (NULL, 'Cleaning Crews', 'Professional cleaning team services'),
  (NULL, 'Closet Design Companies', 'Custom closet design and installation'),
  (NULL, 'Closet Makers', 'Custom closet manufacturing services'),
  (NULL, 'Closets', 'Custom closet design and organization'),
  (NULL, 'Cockroach Control', 'Professional pest control services'),
  (NULL, 'Commercial A/C Repair', 'Commercial HVAC repair services'),
  (NULL, 'Commercial Architects', 'Commercial architectural services'),
  (NULL, 'Commercial Carpet Cleaners', 'Professional carpet cleaning services'),
  (NULL, 'Commercial Carpeting', 'Commercial carpet installation services'),
  (NULL, 'Commercial Cleaning Services', 'Professional commercial cleaning'),
  (NULL, 'Commercial Door Repair', 'Commercial door maintenance services'),
  (NULL, 'Commercial Electricians', 'Professional electrical services'),
  (NULL, 'Commercial Floor Cleaning', 'Professional floor maintenance'),
  (NULL, 'Commercial Insulation', 'Commercial insulation services'),
  (NULL, 'Commercial Landscaping', 'Professional landscaping services'),
  (NULL, 'Commercial Locksmiths', 'Professional locksmith services'),
  (NULL, 'Commercial Painting', 'Professional painting services'),
  (NULL, 'Commercial Pavers', 'Commercial paving services'),
  (NULL, 'Commercial Plumber', 'Professional plumbing services'),
  (NULL, 'Commercial Roofing', 'Commercial roofing services'),
  (NULL, 'Commercial Snow Removal', 'Professional snow removal services'),
  (NULL, 'Commercial Window Companies', 'Commercial window services'),
  (NULL, 'Commercial Window Tinting', 'Professional window tinting services'),
  (NULL, 'Computer Repair Services', 'Professional computer repair'),
  (NULL, 'Concrete Contractors', 'Professional concrete services'),
  (NULL, 'Concrete Cutting', 'Concrete cutting and coring services'),
  (NULL, 'Concrete Delivery Companies', 'Ready-mix concrete delivery services'),
  (NULL, 'Concrete Demolition', 'Professional concrete removal'),
  (NULL, 'Concrete Driveway Companies', 'Driveway installation services'),
  (NULL, 'Concrete Finishing', 'Professional concrete finishing'),
  (NULL, 'Concrete Floor Staining', 'Concrete staining services'),
  (NULL, 'Concrete Flooring', 'Concrete flooring installation'),
  (NULL, 'Concrete Foundation Companies', 'Foundation installation services'),
  (NULL, 'Concrete Leveling', 'Professional concrete leveling'),
  (NULL, 'Concrete Masons', 'Professional masonry services'),
  (NULL, 'Concrete Mudjacking', 'Concrete lifting services'),
  (NULL, 'Concrete Patio Contractors', 'Patio installation services'),
  (NULL, 'Concrete Removal', 'Concrete demolition services'),
  (NULL, 'Concrete Repair', 'Professional concrete repair'),
  (NULL, 'Concrete Resurfacing', 'Concrete restoration services'),
  (NULL, 'Concrete Steps Repair', 'Step repair and installation'),
  (NULL, 'Concrete Walls', 'Concrete wall construction'),
  (NULL, 'Construction Management', 'Project management services'),
  (NULL, 'Copper Gutters', 'Copper gutter installation'),
  (NULL, 'Corian Countertops', 'Countertop installation services'),
  (NULL, 'Couch Cleaning', 'Professional upholstery cleaning'),
  (NULL, 'Couch Removal', 'Furniture removal services'),
  (NULL, 'Couch Repair Services', 'Furniture repair services'),
  (NULL, 'Countertop Installation', 'Professional countertop services'),
  (NULL, 'Countertop Repair', 'Countertop repair services'),
  (NULL, 'Countertop Resurfacing Companies', 'Countertop restoration services'),
  (NULL, 'Crawl Space Encapsulation', 'Moisture control services'),
  (NULL, 'Crown Molding Companies', 'Trim installation services'),
  (NULL, 'Curtain & Drapery Installation', 'Window treatment installation'),
  (NULL, 'Curtain & Drapery Repair', 'Window treatment repair'),
  (NULL, 'Custom Builders', 'Custom construction services'),
  (NULL, 'Custom Furniture Builders', 'Custom furniture manufacturing'),
  (NULL, 'Custom Woodworking', 'Custom woodworking services'),
  (NULL, 'Deck Cleaning Services', 'Professional deck maintenance'),
  (NULL, 'Deck Companies', 'Deck construction services'),
  (NULL, 'Deck Maintenance', 'Deck repair and maintenance'),
  (NULL, 'Deck Painters', 'Professional deck finishing'),
  (NULL, 'Deck Refinishing Services', 'Deck restoration services'),
  (NULL, 'Deck Repair Companies', 'Professional deck repair'),
  (NULL, 'Deck Staining Companies', 'Deck finishing services'),
  (NULL, 'Decks and Porches', 'Outdoor structure construction'),
  (NULL, 'Decorative Concrete', 'Concrete finishing services'),
  (NULL, 'Dehumidifier & Humidifier Repair', 'Appliance repair services'),
  (NULL, 'Demolition Services', 'Professional demolition services'),
  (NULL, 'Dirt Hauling', 'Excavation and hauling services'),
  (NULL, 'Dishwasher Installation', 'Appliance installation services'),
  (NULL, 'Dishwasher Repair', 'Appliance repair services'),
  (NULL, 'Dock Builders', 'Dock construction services'),
  (NULL, 'Dock Building & Repair', 'Marine construction services'),
  (NULL, 'Dog Fence Companies', 'Pet containment systems'),
  (NULL, 'Door Installation', 'Professional door services'),
  (NULL, 'Door Lock Repair Services', 'Lock repair and replacement'),
  (NULL, 'Door Refinishing', 'Door restoration services'),
  (NULL, 'Door Repair', 'Professional door repair'),
  (NULL, 'Doorbell Installation', 'Security system installation'),
  (NULL, 'Doors', 'Door sales and installation'),
  (NULL, 'Drain Cleaning', 'Professional plumbing services'),
  (NULL, 'Drain Contractors', 'Drainage system services'),
  (NULL, 'Drain Pipe Installation', 'Plumbing installation services'),
  (NULL, 'Drapery Alterations', 'Window treatment services'),
  (NULL, 'Drapery Cleaning', 'Professional cleaning services'),
  (NULL, 'Driveway Gates', 'Gate installation services'),
  (NULL, 'Driveway Pavers', 'Paving installation services'),
  (NULL, 'Driveway Paving Companies', 'Asphalt paving services'),
  (NULL, 'Driveway Repair', 'Driveway maintenance services'),
  (NULL, 'Driveway Sealing', 'Asphalt sealing services'),
  (NULL, 'Dryer Repair', 'Appliance repair services'),
  (NULL, 'Dryer Vent Cleaning', 'Maintenance services'),
  (NULL, 'Dryvit Contractors', 'EIFS installation services'),
  (NULL, 'Drywall', 'Drywall installation services'),
  (NULL, 'Drywall & Insulation Contractors', 'Construction services'),
  (NULL, 'Drywall Installers', 'Professional drywall services'),
  (NULL, 'Drywall Repair', 'Wall repair services'),
  (NULL, 'Duct Installers', 'HVAC installation services'),
  (NULL, 'Dumpster Rental', 'Waste management services'),
  (NULL, 'Earth Moving Companies', 'Excavation services'),
  (NULL, 'Earthquake Retrofitting', 'Structural reinforcement'),
  (NULL, 'Egress Window Installers', 'Window installation services'),
  (NULL, 'Egress Windows', 'Safety window installation'),
  (NULL, 'EIFS Contractors', 'Exterior finishing services'),
  (NULL, 'Electric Inspectors', 'Electrical inspection services'),
  (NULL, 'Electric Repair', 'Electrical repair services'),
  (NULL, 'Electric Water Heater Repair Companies', 'Plumbing services'),
  (NULL, 'Electrical', 'Professional electrical services'),
  (NULL, 'Electrical Construction', 'Electrical installation services'),
  (NULL, 'Electrical Handymen', 'Electrical repair services'),
  (NULL, 'Electrical Panel Upgrade', 'Electrical services'),
  (NULL, 'Electrolux Appliance Repair', 'Appliance repair services'),
  (NULL, 'Electrolux Vacuum Repair', 'Vacuum repair services'),
  (NULL, 'Electrolux Washer Repair', 'Appliance repair services'),
  (NULL, 'Elevator Companies', 'Elevator installation services'),
  (NULL, 'Emergency Appliance Repair Companies', 'Urgent repair services'),
  (NULL, 'Emergency Carpet Cleaners', 'Urgent cleaning services'),
  (NULL, 'Emergency Cleaning Services', '24/7 cleaning services'),
  (NULL, 'Emergency Electricians', '24/7 electrical services'),
  (NULL, 'Emergency Garage Door Repair', 'Urgent repair services'),
  (NULL, 'Emergency Handymen', '24/7 repair services'),
  (NULL, 'Emergency Locksmiths', '24/7 locksmith services'),
  (NULL, 'Emergency Plumbers', '24/7 plumbing services'),
  (NULL, 'Emergency Roofing Companies', 'Urgent roof repair'),
  (NULL, 'Energy Efficiency Auditing', 'Energy assessment services'),
  (NULL, 'Entry Door Repair', 'Door repair services'),
  (NULL, 'Epoxy Flooring', 'Floor coating services'),
  (NULL, 'EV Charger Installer', 'Electrical installation services'),
  (NULL, 'Excavating', 'Excavation services'),
  (NULL, 'Excavation Contractors', 'Professional excavation'),
  (NULL, 'Exhaust Fan Installation', 'Ventilation services'),
  (NULL, 'Exterior Painting', 'Professional painting services'),
  (NULL, 'Farmhouse Builders', 'Custom home construction'),
  (NULL, 'Faucet Installation', 'Plumbing installation services'),
  (NULL, 'Faucet Repair', 'Plumbing repair services'),
  (NULL, 'Fence & Gate Repair', 'Fencing repair services'),
  (NULL, 'Fence Installers', 'Fence installation services'),
  (NULL, 'Fence Painting', 'Fence finishing services'),
  (NULL, 'Fence Repair Companies', 'Fencing repair services'),
  (NULL, 'Fence Staining', 'Fence finishing services'),
  (NULL, 'Fencing', 'Fence installation services'),
  (NULL, 'Feng Shui Experts', 'Space optimization services'),
  (NULL, 'Fiber Cement Siding', 'Siding installation services'),
  (NULL, 'Fiberglass Pools', 'Pool installation services'),
  (NULL, 'Fire Damage Restoration', 'Restoration services'),
  (NULL, 'Fire Pit Installation', 'Outdoor feature installation'),
  (NULL, 'Fire Sprinkler Contractors', 'Fire safety services'),
  (NULL, 'Fireplace Builders', 'Fireplace construction'),
  (NULL, 'Fireplace Cleaners', 'Fireplace maintenance'),
  (NULL, 'Fireplace Inspection', 'Safety inspection services');

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_business_services_name ON business_services(name);