-- Insert remaining services
INSERT INTO business_services (business_id, name, description)
VALUES 
  (NULL, 'Paving Contractors', 'Professional paving and asphalt services'),
  (NULL, 'Perc Test Companies', 'Soil percolation testing services'),
  (NULL, 'Pergola Builders', 'Custom pergola design and construction'),
  (NULL, 'Pest Control', 'Professional pest management services'),
  (NULL, 'Pest Control Services', 'Comprehensive pest elimination services'),
  (NULL, 'Pest Inspection', 'Professional pest inspection services'),
  (NULL, 'Pet Door Installation', 'Pet door fitting and installation'),
  (NULL, 'Phone Repair', 'Mobile phone repair services'),
  (NULL, 'Piano Moving', 'Specialized piano relocation services'),
  (NULL, 'Picture Hangers', 'Professional picture hanging services'),
  (NULL, 'Plaster Repair', 'Professional plaster restoration services'),
  (NULL, 'Playground Installation', 'Playground equipment installation'),
  (NULL, 'Playground Repair Services', 'Playground maintenance and repair'),
  (NULL, 'Playgrounds', 'Playground design and construction'),
  (NULL, 'Plumbing', 'Professional plumbing services'),
  (NULL, 'Plumbing & Heating Companies', 'Plumbing and HVAC services'),
  (NULL, 'Plumbing Repairs', 'Plumbing maintenance and repair'),
  (NULL, 'Pole Barn Builders', 'Pole barn construction services'),
  (NULL, 'Pond Companies', 'Pond design and installation'),
  (NULL, 'Pond Services', 'Pond maintenance and repair'),
  (NULL, 'Pool and Spa Service', 'Pool and spa maintenance'),
  (NULL, 'Pool Cleaning', 'Professional pool cleaning services'),
  (NULL, 'Pool Closing Services', 'Seasonal pool winterization'),
  (NULL, 'Pool Cover Repair', 'Pool cover maintenance services'),
  (NULL, 'Pool Deck Companies', 'Pool deck construction services'),
  (NULL, 'Pool Designers', 'Custom pool design services'),
  (NULL, 'Pool Heater Repair', 'Pool heater maintenance services'),
  (NULL, 'Pool Heater Services', 'Pool heating system services'),
  (NULL, 'Pool Inspector', 'Professional pool inspection services'),
  (NULL, 'Pool Liner Replace & Install Companies', 'Pool liner services'),
  (NULL, 'Pool Maintenance', 'Regular pool maintenance services'),
  (NULL, 'Pool Plaster Repair', 'Pool surface repair services'),
  (NULL, 'Pool Pump Repair', 'Pool equipment repair services'),
  (NULL, 'Pool Remodeling Companies', 'Pool renovation services'),
  (NULL, 'Pool Removal Companies', 'Pool demolition services'),
  (NULL, 'Pool Repair', 'General pool repair services'),
  (NULL, 'Pool Resurfacing', 'Pool surface restoration services'),
  (NULL, 'Pool Table Assembly', 'Pool table installation services'),
  (NULL, 'Pool Tile Companies', 'Pool tile installation services'),
  (NULL, 'Popcorn Ceiling', 'Popcorn ceiling services'),
  (NULL, 'Porcelain Bathtub Refinish & Repair', 'Bathtub restoration services'),
  (NULL, 'Porcelain Tile', 'Porcelain tile installation'),
  (NULL, 'Porch Contractors', 'Porch construction services'),
  (NULL, 'Porch Repair', 'Porch maintenance services'),
  (NULL, 'Powder Coating Services', 'Metal finishing services'),
  (NULL, 'Power Washing', 'Pressure cleaning services'),
  (NULL, 'Pre-Made Cabinets', 'Cabinet sales and installation'),
  (NULL, 'Pressure Washing', 'Surface cleaning services'),
  (NULL, 'Privacy Fence Companies', 'Privacy fence installation'),
  (NULL, 'Property Appraiser', 'Property valuation services'),
  (NULL, 'Putting Greens', 'Artificial turf installation'),
  (NULL, 'Quartz Countertop Installers', 'Countertop installation services'),
  (NULL, 'Raccoon Control', 'Wildlife removal services'),
  (NULL, 'Radon Inspectors', 'Radon testing services'),
  (NULL, 'Radon Mitigation', 'Radon reduction services'),
  (NULL, 'Range Hood Companies', 'Range hood installation services'),
  (NULL, 'Real Estate Agents', 'Property sales services'),
  (NULL, 'Realtors', 'Real estate services'),
  (NULL, 'Recessed Lighting Installers', 'Lighting installation services'),
  (NULL, 'Recliner Repair', 'Furniture repair services'),
  (NULL, 'Refrigerator Repair', 'Appliance repair services'),
  (NULL, 'Remodel Designers', 'Renovation design services'),
  (NULL, 'Remodeling - Modular & Mobile Home', 'Mobile home renovation'),
  (NULL, 'Remodeling Basements', 'Basement renovation services'),
  (NULL, 'Residential Cleaners', 'Home cleaning services'),
  (NULL, 'Residential Designers', 'Home design services'),
  (NULL, 'Retaining Wall Companies', 'Wall construction services'),
  (NULL, 'Retaining Wall Repair', 'Wall repair services'),
  (NULL, 'Ring Installers', 'Smart doorbell installation'),
  (NULL, 'Rodent Control', 'Pest control services'),
  (NULL, 'Roof Cleaning', 'Roof maintenance services'),
  (NULL, 'Roof Ice/Snow Removal', 'Winter roof maintenance'),
  (NULL, 'Roof Inspection', 'Roof assessment services'),
  (NULL, 'Roof Moss Removal', 'Roof cleaning services'),
  (NULL, 'Roof Repair', 'Roof maintenance services'),
  (NULL, 'Roof Sealing', 'Roof waterproofing services'),
  (NULL, 'Roofers', 'Roofing services'),
  (NULL, 'Roofing & Siding', 'Exterior construction services'),
  (NULL, 'Rototilling', 'Soil preparation services'),
  (NULL, 'Rubber Roofers', 'Rubber roof installation'),
  (NULL, 'Rug Cleaning', 'Professional rug cleaning'),
  (NULL, 'Safe Installation', 'Security safe installation'),
  (NULL, 'Safe Movers', 'Safe relocation services'),
  (NULL, 'Same Day House Cleaning', 'Urgent cleaning services'),
  (NULL, 'Samsung Appliance Repair', 'Samsung appliance services'),
  (NULL, 'Samsung Dishwasher Repair', 'Dishwasher repair services'),
  (NULL, 'Samsung Dryer Repair', 'Dryer repair services'),
  (NULL, 'Samsung Microwave Repair', 'Microwave repair services'),
  (NULL, 'Samsung Oven Repair', 'Oven repair services'),
  (NULL, 'Samsung Refrigerator Repair', 'Refrigerator repair services'),
  (NULL, 'Samsung Tablet Repair', 'Tablet repair services'),
  (NULL, 'Samsung TV Repair', 'TV repair services'),
  (NULL, 'Samsung Washer Repair', 'Washer repair services'),
  (NULL, 'Sandblasting', 'Surface preparation services'),
  (NULL, 'Satellite Tv', 'Satellite installation services'),
  (NULL, 'Sauna Companies', 'Sauna installation services'),
  (NULL, 'Sauna Repair', 'Sauna maintenance services'),
  (NULL, 'Screen Door Installation', 'Door installation services'),
  (NULL, 'Screen Porch Builders', 'Porch construction services'),
  (NULL, 'Screen repair', 'Screen repair services'),
  (NULL, 'Seamless Gutter Companies', 'Gutter installation services'),
  (NULL, 'Seamless Gutter Repair', 'Gutter repair services'),
  (NULL, 'Security Camera Installation', 'Security system services'),
  (NULL, 'Security Door Installers', 'Security door installation'),
  (NULL, 'Security Monitoring Companies', 'Security monitoring services'),
  (NULL, 'Septic Maintenance Companies', 'Septic system services'),
  (NULL, 'Septic System Repair', 'Septic repair services'),
  (NULL, 'Septic Tank Cleaners', 'Septic cleaning services'),
  (NULL, 'Septic Tank Companies', 'Septic system services'),
  (NULL, 'Septic Tank Service', 'Septic maintenance services'),
  (NULL, 'Sewer Cleaning', 'Sewer maintenance services'),
  (NULL, 'Sewer Companies', 'Sewer service providers'),
  (NULL, 'Sewer Line Repair', 'Sewer repair services'),
  (NULL, 'Shed Builders', 'Custom shed construction'),
  (NULL, 'Shower Door Installers', 'Shower door installation'),
  (NULL, 'Shower Enclosures', 'Shower enclosure installation'),
  (NULL, 'Shower Glass Installers', 'Glass installation services'),
  (NULL, 'Shower Installation', 'Shower installation services'),
  (NULL, 'Shower Repair', 'Shower repair services'),
  (NULL, 'Shrub Removal & Trimming', 'Landscaping services'),
  (NULL, 'Siding', 'Siding installation services'),
  (NULL, 'Siding Companies', 'Siding contractors'),
  (NULL, 'Siding Repair', 'Siding repair services'),
  (NULL, 'Sign Makers', 'Custom sign fabrication'),
  (NULL, 'Sink Installation', 'Plumbing installation services'),
  (NULL, 'Sink Refinishing', 'Sink restoration services'),
  (NULL, 'Sink Repair', 'Plumbing repair services'),
  (NULL, 'Skunk Control', 'Wildlife control services'),
  (NULL, 'Skylight Companies', 'Skylight installation services'),
  (NULL, 'Skylight Repair', 'Skylight maintenance services'),
  (NULL, 'Skylights', 'Skylight sales and installation'),
  (NULL, 'Slate Roofers', 'Slate roofing services'),
  (NULL, 'Sliding Door Installation', 'Door installation services'),
  (NULL, 'Small Appliance Repair Services', 'Appliance repair services'),
  (NULL, 'Small Movers', 'Moving services'),
  (NULL, 'Smartphone Repair', 'Phone repair services'),
  (NULL, 'Smoke Detector Installers', 'Safety device installation'),
  (NULL, 'Smoke Restoration Companies', 'Fire damage restoration'),
  (NULL, 'Snake Control', 'Wildlife removal services'),
  (NULL, 'Snow Removal Companies', 'Snow clearing services'),
  (NULL, 'Sod Installation', 'Lawn installation services'),
  (NULL, 'Sod Removal Services', 'Lawn removal services'),
  (NULL, 'Soil Testing', 'Soil analysis services'),
  (NULL, 'Solar Panel Cleaning', 'Solar maintenance services'),
  (NULL, 'Solar Panel Installation', 'Solar system installation'),
  (NULL, 'Solar Panel Repair', 'Solar system maintenance'),
  (NULL, 'Solar Panels', 'Solar energy systems'),
  (NULL, 'Solar Pool Heater Installers', 'Pool heating installation'),
  (NULL, 'Soundproofing', 'Acoustic treatment services'),
  (NULL, 'Spider Control', 'Pest control services'),
  (NULL, 'Spray Foam Insulation Installers', 'Insulation services'),
  (NULL, 'Sprinkler Services', 'Irrigation system services'),
  (NULL, 'Sprinkler Winterization', 'Seasonal maintenance services'),
  (NULL, 'Squirrel Removal', 'Wildlife control services'),
  (NULL, 'Stained Glass Repair', 'Glass repair services'),
  (NULL, 'Stair Builders', 'Custom stair construction'),
  (NULL, 'Stair Installers', 'Stair installation services'),
  (NULL, 'Stamped Concrete', 'Decorative concrete services'),
  (NULL, 'Stamped Concrete Patio Companies', 'Patio construction services'),
  (NULL, 'Stone and Gravel', 'Landscaping materials'),
  (NULL, 'Stone Countertops', 'Countertop installation'),
  (NULL, 'Stone Flooring Companies', 'Flooring installation services'),
  (NULL, 'Stone Veneer', 'Stone facade installation'),
  (NULL, 'Storm Damage Repair Companies', 'Storm restoration services'),
  (NULL, 'Storm Door Companies', 'Door installation services'),
  (NULL, 'Storm Drain Contractors', 'Drainage system services'),
  (NULL, 'Storm Shelter Builders', 'Shelter construction services'),
  (NULL, 'Structural Engineering', 'Engineering services'),
  (NULL, 'Structural Engineers', 'Engineering consultation'),
  (NULL, 'Stucco', 'Stucco installation services'),
  (NULL, 'Stucco Contractors', 'Stucco application services'),
  (NULL, 'Stucco Repair', 'Stucco maintenance services'),
  (NULL, 'Stump Removal', 'Tree service'),
  (NULL, 'Subcontractors', 'Construction services'),
  (NULL, 'Sump Pump Installation', 'Pump installation services'),
  (NULL, 'Sump Pump Repair', 'Pump repair services'),
  (NULL, 'Sump Pump Replacement', 'Pump replacement services'),
  (NULL, 'Sunrooms', 'Sunroom construction services'),
  (NULL, 'Sunrooms and Patio Enclosures', 'Room addition services'),
  (NULL, 'Surround Sound Installation', 'Audio system installation'),
  (NULL, 'Surveillance Camera Installation', 'Security system services'),
  (NULL, 'Suspended Ceiling Companies', 'Ceiling installation services'),
  (NULL, 'Swamp Cooler Repair', 'Cooling system repair'),
  (NULL, 'Swimming Pool Installation', 'Pool construction services'),
  (NULL, 'Swimming Pools', 'Pool construction and service'),
  (NULL, 'Swing Set Installation', 'Playground equipment installation'),
  (NULL, 'Tankless Water Heater Companies', 'Water heater services'),
  (NULL, 'Tankless Water Heater Repair', 'Water heater repair'),
  (NULL, 'Tennis Court Contractors', 'Court construction services'),
  (NULL, 'Termite Control', 'Pest control services'),
  (NULL, 'Termite Tenting', 'Pest elimination services'),
  (NULL, 'Thermostat Installation', 'HVAC control installation'),
  (NULL, 'Thermostat Repair', 'HVAC control repair'),
  (NULL, 'Tile Contractors', 'Tile installation services'),
  (NULL, 'Tile Floor Cleaning', 'Floor maintenance services'),
  (NULL, 'Tile Floor Installers', 'Flooring installation services'),
  (NULL, 'Tile Grout Cleaners', 'Grout cleaning services'),
  (NULL, 'Tile Repair Companies', 'Tile repair services'),
  (NULL, 'Tile Roof Repair', 'Roof repair services'),
  (NULL, 'Toilet Repair & Installation', 'Plumbing services'),
  (NULL, 'Topsoil Delivery', 'Landscaping material delivery'),
  (NULL, 'Trampoline Assembly', 'Equipment assembly services'),
  (NULL, 'Trash Bin Rental', 'Waste container rental'),
  (NULL, 'Trash Compactor Repair', 'Appliance repair services'),
  (NULL, 'Trash Haulers', 'Waste removal services'),
  (NULL, 'Tree Cutting Services', 'Tree removal services'),
  (NULL, 'Tree Debris Removal & Disposal', 'Yard waste removal'),
  (NULL, 'Tree Maintenance', 'Tree care services'),
  (NULL, 'Tree Planting Services', 'Landscaping services'),
  (NULL, 'Tree Pruning', 'Tree maintenance services'),
  (NULL, 'Tree Removal', 'Tree service'),
  (NULL, 'Tree Service', 'Arborist services'),
  (NULL, 'Tree Surgeons', 'Professional tree care'),
  (NULL, 'Tree Trimming', 'Tree maintenance services'),
  (NULL, 'Treehouse Builders', 'Custom construction services'),
  (NULL, 'Tub to Shower Conversion', 'Bathroom remodeling services'),
  (NULL, 'Tuck Pointers', 'Masonry repair services'),
  (NULL, 'Turf Installation', 'Artificial grass installation'),
  (NULL, 'TV Antenna', 'Antenna installation services'),
  (NULL, 'TV Antenna Services', 'Antenna maintenance services'),
  (NULL, 'TV Mounting', 'TV installation services'),
  (NULL, 'TV Repair', 'Television repair services'),
  (NULL, 'Ultrasonic Cleaning', 'Specialized cleaning services'),
  (NULL, 'Unfinished Carpentry', 'Carpentry services'),
  (NULL, 'Upholstering', 'Furniture upholstery services'),
  (NULL, 'Upholstery Cleaners', 'Furniture cleaning services'),
  (NULL, 'Vertical Blind Repair', 'Blind repair services'),
  (NULL, 'Vinyl Fencing Installers', 'Fence installation services'),
  (NULL, 'Vinyl Floor Repair', 'Flooring repair services'),
  (NULL, 'Vinyl Flooring Companies', 'Flooring installation services'),
  (NULL, 'Vinyl Siding Cleaning', 'Siding maintenance services'),
  (NULL, 'Vinyl Siding Repair Contractors', 'Siding repair services'),
  (NULL, 'Walk-In Tub Installers', 'Bathroom modification services'),
  (NULL, 'Wall Heater Repair', 'Heating system repair'),
  (NULL, 'Wall Painters', 'Painting services'),
  (NULL, 'Wall Repair Services', 'Wall repair services'),
  (NULL, 'Wallpaper Installers', 'Wallpaper installation services'),
  (NULL, 'Wallpaper Removal', 'Wallpaper removal services'),
  (NULL, 'Wallpapering', 'Wallpaper installation services'),
  (NULL, 'Washing Machine Repair', 'Appliance repair services'),
  (NULL, 'Waste Removal Companies', 'Waste management services'),
  (NULL, 'Water and Smoke Damage', 'Damage restoration services'),
  (NULL, 'Water Clean Up', 'Water damage restoration'),
  (NULL, 'Water Damage Companies', 'Restoration services'),
  (NULL, 'Water Feature Companies', 'Water feature installation'),
  (NULL, 'Water Filtration and Softening', 'Water treatment services'),
  (NULL, 'Water Heater Installation', 'Plumbing installation services'),
  (NULL, 'Water Heater Repair', 'Plumbing repair services'),
  (NULL, 'Water Heaters', 'Water heater sales and service'),
  (NULL, 'Water Line Installation', 'Plumbing installation services'),
  (NULL, 'Water Line Repair', 'Plumbing repair services'),
  (NULL, 'Water Softener Companies', 'Water treatment services'),
  (NULL, 'Water Softener Repair Companies', 'Water system repair'),
  (NULL, 'Water Softener Specialists', 'Water treatment experts'),
  (NULL, 'Weed Control', 'Lawn care services'),
  (NULL, 'Welders', 'Welding services'),
  (NULL, 'Welding', 'Metal fabrication services'),
  (NULL, 'Well Pump Companies', 'Well system services'),
  (NULL, 'Well Pump Repair', 'Pump repair services'),
  (NULL, 'Wells and Pumps', 'Well system services'),
  (NULL, 'Wheelchair Ramp Companies', 'Accessibility construction'),
  (NULL, 'Whirlpool Dryer Repair', 'Appliance repair services'),
  (NULL, 'Whirlpool Oven Repair', 'Appliance repair services'),
  (NULL, 'Whirlpool Refrigerator Repair', 'Appliance repair services'),
  (NULL, 'Whirlpool Repair', 'Appliance repair services'),
  (NULL, 'Whirlpool Washer Repair', 'Appliance repair services'),
  (NULL, 'Wicker Repair', 'Furniture repair services'),
  (NULL, 'Wildlife Control', 'Animal control services'),
  (NULL, 'Window & Door Installation', 'Installation services'),
  (NULL, 'Window A/C Repair', 'AC repair services'),
  (NULL, 'Window Glass Repair', 'Glass repair services'),
  (NULL, 'Window Glass Replacement', 'Glass replacement services'),
  (NULL, 'Window Installation', 'Window installation services'),
  (NULL, 'Window Screen Installation', 'Screen installation services'),
  (NULL, 'Window Screen Repair Companies', 'Screen repair services'),
  (NULL, 'Window Shade Repair', 'Shade repair services'),
  (NULL, 'Window Shutter Companies', 'Shutter installation services'),
  (NULL, 'Window Shutter Repair', 'Shutter repair services'),
  (NULL, 'Window Tinting', 'Window film installation'),
  (NULL, 'Window Treatments', 'Window covering services'),
  (NULL, 'Window Washers', 'Window cleaning services'),
  (NULL, 'Windows', 'Window sales and installation'),
  (NULL, 'Wood & Pellet Stove Repair', 'Stove repair services'),
  (NULL, 'Wood Fence Companies', 'Fence installation services'),
  (NULL, 'Wood Fence Repair', 'Fence repair services'),
  (NULL, 'Wood Floor Refinishing', 'Floor restoration services'),
  (NULL, 'Wood Stove Inspection', 'Stove inspection services'),
  (NULL, 'Wood Stove Services', 'Stove maintenance services'),
  (NULL, 'Wood Stripping Services', 'Wood refinishing services'),
  (NULL, 'Woodworking', 'Custom woodworking services'),
  (NULL, 'Wrought Iron', 'Iron work services'),
  (NULL, 'Wrought Iron Fence Repair', 'Fence repair services'),
  (NULL, 'Wrought Iron Fences', 'Fence installation services'),
  (NULL, 'Yard Clean Up Services', 'Yard maintenance services');