/*
  # Add additional services

  1. Changes
    - Add new services to the services table
    - Handle duplicates by checking existence
*/

-- Insert new services if they don't exist
INSERT INTO services (name)
SELECT name
FROM (VALUES
  ('Air Duct Cleaning'),
  ('Animal Removal'),
  ('Antenna Repair'),
  ('Appliance Repair'),
  ('Architect'),
  ('Asbestos Removal'),
  ('Awnings'),
  ('Basement Remodeling'),
  ('Basement Waterproofing'),
  ('Basketball Hoop Installation'),
  ('Bathtub Refinishing'),
  ('Biohazard Cleanup'),
  ('Blind Cleaning'),
  ('Cabinet Makers'),
  ('Cabinet Refacing'),
  ('Carpet Cleaning'),
  ('Carpet Installation'),
  ('Ceiling Fan Installation'),
  ('Central Vacuum Cleaning'),
  ('Childproofing'),
  ('Chimney Cap Repair'),
  ('Chimney Repair'),
  ('Chimney Sweep'),
  ('Cleaning Services'),
  ('Closet Design'),
  ('Computer Repair'),
  ('Concrete Driveways'),
  ('Concrete Repair'),
  ('Countertop Installation'),
  ('Deck Cleaning'),
  ('Decks & Porches'),
  ('Dock Building'),
  ('Dog Fencing'),
  ('Door Installation'),
  ('Drain Cleaning'),
  ('Drain Pipe Installation'),
  ('Drapery Cleaning'),
  ('Driveway Gate Installation'),
  ('Driveway Pavers'),
  ('Dryer Vent Cleaning'),
  ('Drywall'),
  ('Dumpster Rental'),
  ('Earthquake Retrofitting'),
  ('Egress Window'),
  ('Electrician'),
  ('Epoxy Flooring'),
  ('Excavating'),
  ('Fence Company'),
  ('Fireplace Services'),
  ('Floor Buffing'),
  ('Floor Cleaning'),
  ('Flooring'),
  ('Foundation Repair'),
  ('Fountains'),
  ('Furniture Refinishing'),
  ('Garage Building'),
  ('Garage Doors'),
  ('Gas Fireplace Repair'),
  ('Gas Leak Repair'),
  ('General Contractors'),
  ('Generator Service'),
  ('Glass Block'),
  ('Glass Repair'),
  ('Grill Repair'),
  ('Gutter Cleaning'),
  ('Gutter Repair'),
  ('Handyman'),
  ('Hardscaping'),
  ('Hardwood Floors'),
  ('Hauling'),
  ('Heating Oil Company'),
  ('Holiday Decorating'),
  ('Home Automation'),
  ('Home Builder'),
  ('Home Energy Audit'),
  ('Home Inspection'),
  ('Home Remodeling'),
  ('Home Security Systems'),
  ('Home Staging'),
  ('Home Theater Installation'),
  ('Home Warranty'),
  ('House Cleaning'),
  ('House Painting'),
  ('Hurricane Shutters'),
  ('HVAC Companies'),
  ('Insulation'),
  ('Interior Decorators'),
  ('Interior Painting'),
  ('Iron Work'),
  ('Irrigation System'),
  ('Jewelry Appraising'),
  ('Land Surveyors'),
  ('Landscape Lighting'),
  ('Large Appliances'),
  ('Lawn & Landscaping'),
  ('Lawn Care'),
  ('Lawn Mower Repair'),
  ('Lawn Treatment'),
  ('Lead Paint Removal'),
  ('Leaf Removal'),
  ('Leather Repair'),
  ('Lighting'),
  ('Locksmith'),
  ('Mailbox Repair'),
  ('Marble & Granite'),
  ('Masonry'),
  ('Metal Fabrication'),
  ('Mobile Home Remodeling'),
  ('Mold Removal'),
  ('Movers'),
  ('Mudjacking'),
  ('Mulch Delivering'),
  ('Nurseries'),
  ('Oriental Rug Cleaning'),
  ('Outdoor Kitchens'),
  ('Patio Enclosures'),
  ('Patios'),
  ('Pest Control'),
  ('Phone Company'),
  ('Phone Repair'),
  ('Piano Movers'),
  ('Plastering'),
  ('Playground Equipment Installation'),
  ('Plumbers'),
  ('Pool Cleaning'),
  ('Pool Installers'),
  ('Pressure Washing'),
  ('Professional Organizers'),
  ('Radon Mitigation'),
  ('Real Estate Agent'),
  ('Real Estate Appraising'),
  ('Roof Cleaning'),
  ('Roof Snow Removal'),
  ('Roofing'),
  ('Rototilling'),
  ('Satellite Tv'),
  ('Screen Repair'),
  ('Septic Tank Service'),
  ('Sewer Cleaning'),
  ('Siding Companies'),
  ('Skylight Installation'),
  ('Small Appliance Repair'),
  ('Snow Removal'),
  ('Solar Companies'),
  ('Stamped Concrete'),
  ('Stone & Gravel'),
  ('Structural Engineering'),
  ('Stucco'),
  ('Tile Installation'),
  ('Trash Removal'),
  ('Tree Service'),
  ('Upholstery'),
  ('Upholstery Cleaning'),
  ('Wallpaper Hanger'),
  ('Wallpaper Removal'),
  ('Water Damage Restoration'),
  ('Water Heaters'),
  ('Water Softeners'),
  ('Welding'),
  ('Well & Water Pump Repair'),
  ('Window Cleaning'),
  ('Window Replacement'),
  ('Window Security Film'),
  ('Window Tinting'),
  ('Window Treatment'),
  ('Woodworking')
) AS t(name)
WHERE NOT EXISTS (
  SELECT 1 FROM services WHERE services.name = t.name
);